### ISSUE TITLE
🎮 Wii U guide (CEMU) 

### ISSUE THREAD

**Issue by n1ckoates** [nchristopher/steamdeck-emulation#2]

**Comment by walllable** [comment]
I got this set up! There's a couple notes though.
General notes:
- If you store your games on your SD card, you'll have to add `STEAM_COMPAT_MOUNTS=/run/media/ %command%` to the launch options in order to access them in Cemu's file browsers. If you use Steam ROM Manager, this applies even if you have both Cemu and your games on the SD card.

Steam ROM Manager related notes:
- In the command line arguments, before ${filepath} add `Z:`. This is required since Cemu will be expecting a Windows-like filepath, as opposed to a Linux filepath.
- If your ROMs (or Cemu's executable, or anything really) is on the SD card, you'll have to copy the filepaths from Dolphin/your file browser into the respective text box, since SRM's included file browser doesn't seem to have access to the SD card.

To add games (and mount your mlc,) open up Cemu, and go to Options > General Settings at the top. Click "Add" under the "Game Paths" section, click on `My Computer`, and then click on `Z:`. From here on it's pretty similar to a regular Linux file layout. If your games are on your SD card, navigate to `run\media\`, and in here you should see the name that you assigned to your SD card. Click in there, and navigate to where you saved your games. The case is pretty much the same if you want to set a custom MLC directory - Just click on the `...` button next to the MLC path textbox, and browse either to where Cemu keeps it if you've downloaded Cemu to your SD card (`Z:/run/media/sd_card_name_here/emulators/cemu_1.26.2/mlc01`) or to wherever on the SD card you want

Now, here's the directions for setting up Steam ROM Emulator for CEMU. The following only applies to extracted/.rpx files, though I imagine it should be pretty similar for other filetypes. Hopefully these instructions aren't too disjointed. I'm going to be working off of the "Generic" community preset.

- Scroll down all the way to the bottom, and enable "Show advanced options."
- Under "Executable" put the path to where Cemu's executable is. In my case, since I have it on my SD card named "Deck," it's `/run/media/Deck/emulators/cemu_1.26.2/Cemu.exe`
- Enable "Append arguments to executable" if it's not enabled already
- Under "Command line arguments," enter `-f -g "Z:${filePath}"` (`-f` makes the game fullscreen, `-g` tells Cemu that this is a path to a game.) We put `Z:` before `${filepath}` since Cemu expects a Windows-like filepath, not a Linux-like filepath.
- Under "User's glob," put `${title}/*/*@(.rpx|.RPX)` so that SRM only parses .rpx files.
- Under "Local Icons," put `${dir}/../*${/\[.*?\]/g|${title}|}*/meta/iconTex.tga`

Once you've tested your parser, gone to the "Preview" section, and added your games to Steam, you should be all set! If you have your games on your SD card, you'll have to add `STEAM_COMPAT_MOUNTS=/run/media/ %command%` to your launch options in each game, so that Cemu can access them. This is also the case if your MLC is stored on your SD card.

As a final note, here's a copy of my configuration, in case I missed anything.
```

# Parser type

····Selected: Glob

# Configuration title

····Cemu (RPX)

# Steam category

····${Wii U}

# Executable

····/run/media/Deck/emulators/cemu_1.26.2/Cemu.exe

····[ ]: Follow .lnk to destination (Windows only)

····[x]: Append arguments to executable

# Command line arguments

····-f -g "Z:${filePath}"

# Executable modifier

····"${exePath}"

# ROMs directory

····/run/media/Deck/emulators/cemu_1.26.2/Games/

# Steam directory

····${steamdirglobal}

# "Start In" directory

····

# User accounts

····

····[x]: Skip found accounts with missing data directories

····[x]: Use account credentials

# Image providers

····Selected: SteamGridDB

# User's glob

····${title}/*/*@(.rpx|.RPX)

# User's glob-regex

····null

# Manifests Directory Override

····null

····[ ]: Launch games via Epic for online services

# Galaxy Path Override

····null

····[ ]: Launch games via GOG Galaxy

# Title from custom variable

····

····[ ]: Case-insensitive variables

····[ ]: Skip file if variable was not found

····[ ]: Enable Title from Custom Variable

# Title modifier

····${fuzzyTitle}

# Fuzzy matching

····[x]: Use fuzzy matching

····[x]: Replace diacritic characters

····[x]: Aggressive matching

····[x]: Remove (...) and [...] brackets

# Online image query

····${${fuzzyTitle}}

# Image pool

····${fuzzyTitle}

# Default image

····

# Default tall image

····

# Default hero image

····

# Default logo image

····

# Default icon

····

# Local images

····

# Local tall images

····

# Local hero images

····

# Local logo images

····

# Local icons

····${dir}/../*${/\[.*?\]/g|${title}|}*/meta/iconTex.tga

····[x]: Disable current parser

····[x]: Show advanced options

```

**Comment by nchristopher** [comment]
Awesome, thanks for the node about SD cards, I'll make sure to add that to the guide.

**Comment by walllable** [comment]
It worked just fine for me under Proton. I'll note though, I had to use Proton 7.0-1, not Proton Experimental. I'll also note that BotW didn't run very well (20fps in the starting cave area thing) until I enabled FPS++ and set it to 30 FPS. Then it was pretty much locked to that, in my short experience with the game so far.

Another thing I want to add that isn't really related to Cemu is that you can allow Flatpaks (Which is probably how you'll be installing these emulators) to access the SD card by running `
flatpak override <package_name_here> --filesystem=/run/media/`, and you can find the flatpak's package name by navigating to `/home/deck/.var/app/`, which is where the files for installed flatpaks are kept. For example, retroarch is `org.libretro.RetroArch`, RPCS3 is `net.rpcs3.RPCS3`, etc.

**Comment by depinav** [comment]
One thing not mentioned here that I needed to do after SRM created the steam shortcuts was check "Force Proton" checkbox for the game shortcuts in steam or else the games wouldn't run. Idk if this is actually necessary or I missed something in the setup, but otherwise I couldn't launch the games from steam.

**Comment by komali2** [comment]
see also https://www.reddit.com/r/SteamDeck/comments/tckji0/guide_on_how_to_install_cemu_on_steam_deck/
