### ISSUE TITLE
🎮 Linux Applications

### ISSUE THREAD

**Issue by jacob99200** [nchristopher/steamdeck-emulation#38]
### System

Linux/PC

### Additional info

On Windows, you use the "Non Steam PC" to detect a folder full of shortcuts and add games

Wanted to see if it was possible to get a tutorial on how to add create shortcuts and add them to steam via the Steam Rom Manager

**Comment by nchristopher** [comment]
I'm not sure if I understand - if you just want to add a shortcut to a non-steam game, you can do that in desktop mode via **Games > Add a Non-Steam Game to My library** in Steam.

Could you provide more context?

**Comment by jacob99200** [comment]
Basically on Windows you're able to use the config "Non Steam PC" and direct it to a folder of shortcuts of games and programs

This will add them to steam and let you use SRM to put them into categories and apply the appropriate artwork in a quick and simple manor

I was looking for a tutorial for making this work on the SD

I attempted to do this by modifying the glob to also look for .desktop files, then had a folder full of them for different programs in games

SRM added them to steam and applied the correct artwork, but when attempting to launch the games it simple doesn't open anything

**Comment by nchristopher** [comment]
Looking into this, I think it's because Steam can execute `.lnk` files (Windows shortcuts), but not `.desktop` files. Extracting the `Exec=` field from a `.desktop` file would have to be done in Steam ROM Manager itself, and is thus out of scope for this guide.

I'd recommend opening an issue [on their repository](https://github.com/SteamGridDB/steam-rom-manager).
